-- Agenix Hive foundation v0
-- Applied to Botanic Creations Supabase on 2026-08-07.
-- Portable PostgreSQL/Supabase schema. Product-private state remains in the owning service.

create schema agenix_hive;
create schema agenix_hive_private;

create table agenix_hive.organizations (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  status text not null default 'active' check (status in ('active','paused','archived')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table agenix_hive.projects (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  slug text not null,
  name text not null,
  status text not null default 'active' check (status in ('active','paused','completed','archived')),
  external_refs jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, slug)
);

create table agenix_hive.memberships (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('owner','admin','operator','reviewer','member','viewer')),
  status text not null default 'active' check (status in ('active','invited','suspended','revoked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (organization_id, user_id)
);

create or replace function agenix_hive_private.is_org_member(p_org_id uuid)
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, agenix_hive
as $$
  select exists (
    select 1 from agenix_hive.memberships m
    where m.organization_id = p_org_id
      and m.user_id = auth.uid()
      and m.status = 'active'
  );
$$;

create or replace function agenix_hive_private.is_any_member()
returns boolean
language sql
stable
security definer
set search_path = pg_catalog, agenix_hive
as $$
  select exists (
    select 1 from agenix_hive.memberships m
    where m.user_id = auth.uid()
      and m.status = 'active'
  );
$$;

create table agenix_hive.providers (
  id uuid primary key default gen_random_uuid(),
  provider_key text not null unique,
  app_slug text,
  display_name text not null,
  role text not null,
  version text not null default '0.1.0',
  status text not null default 'registered' check (status in ('registered','healthy','degraded','offline','disabled')),
  interfaces jsonb not null default '{}'::jsonb,
  owns jsonb not null default '[]'::jsonb,
  requires_approval jsonb not null default '[]'::jsonb,
  manifest jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table agenix_hive.capabilities (
  id bigint generated by default as identity primary key,
  capability_key text not null unique,
  description text not null default '',
  risk_class text not null default 'low' check (risk_class in ('low','medium','high','critical')),
  default_approval text not null default 'automatic' check (default_approval in ('automatic','supervised','human_required','denied')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table agenix_hive.provider_capabilities (
  provider_id uuid not null references agenix_hive.providers(id) on delete cascade,
  capability_id bigint not null references agenix_hive.capabilities(id) on delete cascade,
  enabled boolean not null default true,
  interface_order jsonb not null default '["api","mcp","cli","browser","gui"]'::jsonb,
  config jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (provider_id, capability_id)
);

create table agenix_hive.provider_health (
  provider_id uuid primary key references agenix_hive.providers(id) on delete cascade,
  status text not null default 'unknown' check (status in ('unknown','healthy','degraded','offline')),
  version text,
  latency_ms integer,
  details jsonb not null default '{}'::jsonb,
  last_checked_at timestamptz,
  updated_at timestamptz not null default now()
);

create table agenix_hive.state_domains (
  domain_key text primary key,
  owner_provider_id uuid not null references agenix_hive.providers(id) on delete restrict,
  description text not null default '',
  write_policy jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table agenix_hive.command_sessions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete set null,
  user_id uuid references auth.users(id) on delete set null,
  channel text not null default 'text' check (channel in ('text','voice','api','automation')),
  status text not null default 'active' check (status in ('active','closed','expired')),
  context jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table agenix_hive.commands (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references agenix_hive.command_sessions(id) on delete cascade,
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete set null,
  correlation_id uuid not null default gen_random_uuid(),
  raw_input text not null,
  input_kind text not null default 'text' check (input_kind in ('text','voice_transcript','api','automation')),
  parsed_intent jsonb not null default '{}'::jsonb,
  status text not null default 'received' check (status in ('received','parsed','routed','running','waiting_approval','completed','failed','cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table agenix_hive.runs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete set null,
  command_id uuid references agenix_hive.commands(id) on delete set null,
  correlation_id uuid not null,
  objective text not null,
  status text not null default 'queued' check (status in ('queued','running','blocked','waiting_approval','completed','failed','cancelled')),
  budget_usd numeric(12,4) not null default 0 check (budget_usd >= 0),
  spent_usd numeric(12,4) not null default 0 check (spent_usd >= 0),
  policy_snapshot jsonb not null default '{}'::jsonb,
  metadata jsonb not null default '{}'::jsonb,
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table agenix_hive.run_steps (
  id bigint generated by default as identity primary key,
  run_id uuid not null references agenix_hive.runs(id) on delete cascade,
  step_key text not null,
  sequence_no integer not null default 0,
  provider_id uuid references agenix_hive.providers(id) on delete set null,
  capability_key text,
  status text not null default 'queued' check (status in ('queued','leased','running','blocked','waiting_approval','completed','failed','cancelled','skipped')),
  input_manifest jsonb not null default '{}'::jsonb,
  output_manifest jsonb not null default '{}'::jsonb,
  cost_usd numeric(12,4) not null default 0 check (cost_usd >= 0),
  started_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (run_id, step_key)
);

create table agenix_hive.resource_leases (
  id uuid primary key default gen_random_uuid(),
  resource_key text not null,
  resource_type text not null,
  mode text not null default 'write' check (mode in ('read','write','execute')),
  run_id uuid not null references agenix_hive.runs(id) on delete cascade,
  provider_id uuid references agenix_hive.providers(id) on delete set null,
  lease_token uuid not null default gen_random_uuid() unique,
  acquired_at timestamptz not null default now(),
  expires_at timestamptz not null,
  released_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);

create unique index agenix_hive_one_active_write_lease
  on agenix_hive.resource_leases(resource_key)
  where mode = 'write' and released_at is null;
create index agenix_hive_resource_leases_expiry_idx
  on agenix_hive.resource_leases(expires_at) where released_at is null;

create table agenix_hive.events (
  id bigint generated by default as identity primary key,
  event_uuid uuid not null default gen_random_uuid() unique,
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete set null,
  run_id uuid references agenix_hive.runs(id) on delete cascade,
  correlation_id uuid not null,
  causation_id uuid,
  source_provider_id uuid references agenix_hive.providers(id) on delete set null,
  event_type text not null,
  payload jsonb not null default '{}'::jsonb,
  idempotency_key text not null,
  occurred_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (source_provider_id, idempotency_key)
);
create index agenix_hive_events_correlation_idx on agenix_hive.events(correlation_id, id);
create index agenix_hive_events_run_idx on agenix_hive.events(run_id, id);
create index agenix_hive_events_type_idx on agenix_hive.events(event_type, occurred_at desc);

create table agenix_hive.event_deliveries (
  event_id bigint not null references agenix_hive.events(id) on delete cascade,
  consumer_provider_id uuid not null references agenix_hive.providers(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','delivering','delivered','failed','dead_letter')),
  attempts integer not null default 0 check (attempts >= 0),
  next_attempt_at timestamptz,
  delivered_at timestamptz,
  last_error text,
  updated_at timestamptz not null default now(),
  primary key (event_id, consumer_provider_id)
);

create table agenix_hive.artifacts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete set null,
  run_id uuid references agenix_hive.runs(id) on delete set null,
  step_id bigint references agenix_hive.run_steps(id) on delete set null,
  artifact_type text not null,
  uri text not null,
  sha256 text,
  media_type text,
  size_bytes bigint check (size_bytes is null or size_bytes >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table agenix_hive.evidence_receipts (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete set null,
  run_id uuid not null references agenix_hive.runs(id) on delete cascade,
  step_id bigint references agenix_hive.run_steps(id) on delete set null,
  provider_id uuid references agenix_hive.providers(id) on delete set null,
  status text not null check (status in ('pass','fail','partial','blocked')),
  summary text not null,
  tests jsonb not null default '[]'::jsonb,
  artifacts jsonb not null default '[]'::jsonb,
  cost jsonb not null default '{}'::jsonb,
  verification jsonb not null default '{}'::jsonb,
  signed_at timestamptz not null default now()
);

create table agenix_hive.approvals (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete set null,
  run_id uuid references agenix_hive.runs(id) on delete cascade,
  approval_key text not null,
  action_class text not null,
  risk_class text not null check (risk_class in ('low','medium','high','critical')),
  requested_by_provider uuid references agenix_hive.providers(id) on delete set null,
  status text not null default 'pending' check (status in ('pending','approved','rejected','expired','cancelled')),
  request jsonb not null default '{}'::jsonb,
  decision_by uuid references auth.users(id) on delete set null,
  rationale text,
  requested_at timestamptz not null default now(),
  decided_at timestamptz,
  unique (run_id, approval_key)
);

create table agenix_hive.context_snapshots (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete set null,
  run_id uuid not null references agenix_hive.runs(id) on delete cascade,
  snapshot_kind text not null,
  content jsonb not null,
  content_hash text,
  created_at timestamptz not null default now()
);

create table agenix_hive.policy_versions (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete cascade,
  policy_key text not null,
  version integer not null check (version > 0),
  status text not null default 'active' check (status in ('draft','active','retired')),
  rules jsonb not null default '{}'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
create unique index agenix_hive_policy_version_unique
  on agenix_hive.policy_versions(organization_id, coalesce(project_id, '00000000-0000-0000-0000-000000000000'::uuid), policy_key, version);

create table agenix_hive.external_refs (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete set null,
  entity_type text not null,
  entity_id text not null,
  provider_id uuid references agenix_hive.providers(id) on delete cascade,
  external_type text not null,
  external_id text not null,
  url text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (provider_id, external_type, external_id)
);

create table agenix_hive.audit_log (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references agenix_hive.organizations(id) on delete cascade,
  project_id uuid references agenix_hive.projects(id) on delete set null,
  run_id uuid references agenix_hive.runs(id) on delete set null,
  actor_type text not null,
  actor_id text,
  action text not null,
  object_type text not null,
  object_id text,
  payload_redacted jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function agenix_hive_private.set_updated_at()
returns trigger language plpgsql security definer set search_path = pg_catalog as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

do $$
declare t text;
begin
  foreach t in array array[
    'organizations','projects','memberships','providers','provider_capabilities','provider_health',
    'state_domains','command_sessions','commands','runs','run_steps','event_deliveries'
  ] loop
    execute format('create trigger %I_set_updated_at before update on agenix_hive.%I for each row execute function agenix_hive_private.set_updated_at()', t, t);
  end loop;
end $$;

insert into platform.app_registry (
  app_slug, app_name, schema_name, repository, owner, database_provider,
  storage_namespace, tenancy_model, status, migration_status, metadata
) values (
  'agenix-hive','Agenix Hive','agenix_hive',
  'https://github.com/executiveusa/ascend-social-purpose-agentic-systems-',
  'The Pauli Effect','supabase','agenix-hive','organization','active','managed_supabase',
  jsonb_build_object(
    'purpose','federated agent control plane',
    'portable_to_self_host',true,
    'project_ref','cyxdevcjycmffhmwxojh',
    'cross_repo_writes','lease_required',
    'direct_client_writes','deny_by_default'
  )
)
on conflict (app_slug) do update set
  app_name=excluded.app_name, schema_name=excluded.schema_name, repository=excluded.repository,
  owner=excluded.owner, database_provider=excluded.database_provider,
  storage_namespace=excluded.storage_namespace, tenancy_model=excluded.tenancy_model,
  status=excluded.status, migration_status=excluded.migration_status,
  metadata=platform.app_registry.metadata || excluded.metadata, updated_at=now();

insert into agenix_hive.providers (provider_key, app_slug, display_name, role, interfaces, owns, requires_approval, manifest)
values
  ('agenix-governor','agenix-hive','Agenix Governor','governance','{"api":true,"mcp":false,"cli":false}'::jsonb,'["project_policy","project_context","acceptance_evidence"]'::jsonb,'["publish","destructive_production_change"]'::jsonb,'{"repository":"executiveusa/ascend-social-purpose-agentic-systems-"}'::jsonb),
  ('paperclip-hq',null,'Paperclip HQ','management','{"api":true,"mcp":false,"cli":true}'::jsonb,'["organization_work_state","budgets","delegation"]'::jsonb,'["agent_hire","budget_override"]'::jsonb,'{"repository":"executiveusa/paperclip-pauli-clip"}'::jsonb),
  ('darya-openhands',null,'Darya / OpenHands','software_factory','{"api":true,"mcp":true,"cli":true}'::jsonb,'["engineering_execution_state"]'::jsonb,'["merge_protected_branch","production_deploy"]'::jsonb,'{"repository":"executiveusa/Darya-designs"}'::jsonb),
  ('montage',null,'Montage / OpenMontage','film_studio','{"api":true,"mcp":true,"cli":true}'::jsonb,'["video_project_state","timeline_state","editorial_state"]'::jsonb,'["publish","source_delete"]'::jsonb,'{"repository":"executiveusa/pauli-montage-video-agent"}'::jsonb),
  ('open-interpreter',null,'Open Interpreter','computer_operations','{"api":false,"mcp":true,"cli":true,"browser":true,"gui":true}'::jsonb,'["computer_execution_sessions"]'::jsonb,'["destructive_file_operation","production_infrastructure_change","external_publish"]'::jsonb,'{"repository":"executiveusa/open-interpreter-fork"}'::jsonb)
on conflict (provider_key) do nothing;

insert into agenix_hive.capabilities (capability_key, description, risk_class, default_approval)
values
  ('project.context.load','Load bounded project context','low','automatic'),
  ('work.assign','Assign work to a capability provider','low','automatic'),
  ('software.inspect','Inspect repository/software state','low','automatic'),
  ('software.implement','Implement code in an isolated branch','medium','supervised'),
  ('software.test','Run software tests','low','automatic'),
  ('software.pull_request','Open/update a pull request','medium','supervised'),
  ('video.ingest','Register immutable source media','low','automatic'),
  ('video.transcribe','Transcribe local media','low','automatic'),
  ('video.edit.propose','Propose reversible editorial operations','low','automatic'),
  ('video.edit.apply','Apply reversible edit operations','medium','supervised'),
  ('video.render','Render local media output','low','automatic'),
  ('video.verify','Verify media and visual output','low','automatic'),
  ('computer.shell.execute','Execute bounded shell commands','medium','supervised'),
  ('computer.browser.control','Control browser within allowlisted scope','medium','supervised'),
  ('computer.desktop.control','Control desktop application','high','human_required'),
  ('computer.files.write','Write within approved filesystem roots','medium','supervised'),
  ('external.publish','Publish externally','critical','human_required')
on conflict (capability_key) do nothing;

insert into agenix_hive.state_domains (domain_key, owner_provider_id, description, write_policy)
select v.domain_key, p.id, v.description, v.write_policy
from (values
  ('project_policy','agenix-governor','Client/project policy and acceptance truth','{"cross_provider_write":"deny"}'::jsonb),
  ('organization_work_state','paperclip-hq','Goals, tasks, budgets, delegation and agent lifecycle','{"cross_provider_write":"contract_only"}'::jsonb),
  ('engineering_execution_state','darya-openhands','Software engineering execution sessions','{"cross_provider_write":"deny"}'::jsonb),
  ('video_project_state','montage','Canonical video project and timeline state','{"cross_provider_write":"operations_only"}'::jsonb),
  ('computer_execution_sessions','open-interpreter','Bounded local computer execution state','{"cross_provider_write":"deny"}'::jsonb)
) as v(domain_key, provider_key, description, write_policy)
join agenix_hive.providers p on p.provider_key=v.provider_key
on conflict (domain_key) do update set
  owner_provider_id=excluded.owner_provider_id,
  description=excluded.description,
  write_policy=excluded.write_policy,
  updated_at=now();

-- RLS: authenticated users are organization-scoped read-only; trusted service workers perform writes.
alter table agenix_hive.organizations enable row level security;
alter table agenix_hive.projects enable row level security;
alter table agenix_hive.memberships enable row level security;
alter table agenix_hive.providers enable row level security;
alter table agenix_hive.capabilities enable row level security;
alter table agenix_hive.provider_capabilities enable row level security;
alter table agenix_hive.provider_health enable row level security;
alter table agenix_hive.state_domains enable row level security;
alter table agenix_hive.command_sessions enable row level security;
alter table agenix_hive.commands enable row level security;
alter table agenix_hive.runs enable row level security;
alter table agenix_hive.run_steps enable row level security;
alter table agenix_hive.resource_leases enable row level security;
alter table agenix_hive.events enable row level security;
alter table agenix_hive.event_deliveries enable row level security;
alter table agenix_hive.artifacts enable row level security;
alter table agenix_hive.evidence_receipts enable row level security;
alter table agenix_hive.approvals enable row level security;
alter table agenix_hive.context_snapshots enable row level security;
alter table agenix_hive.policy_versions enable row level security;
alter table agenix_hive.external_refs enable row level security;
alter table agenix_hive.audit_log enable row level security;

create policy organizations_member_read on agenix_hive.organizations for select to authenticated using (agenix_hive_private.is_org_member(id));
create policy projects_member_read on agenix_hive.projects for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy memberships_member_read on agenix_hive.memberships for select to authenticated using (user_id=auth.uid() or agenix_hive_private.is_org_member(organization_id));
create policy providers_member_read on agenix_hive.providers for select to authenticated using (agenix_hive_private.is_any_member());
create policy capabilities_member_read on agenix_hive.capabilities for select to authenticated using (agenix_hive_private.is_any_member());
create policy provider_capabilities_member_read on agenix_hive.provider_capabilities for select to authenticated using (agenix_hive_private.is_any_member());
create policy provider_health_member_read on agenix_hive.provider_health for select to authenticated using (agenix_hive_private.is_any_member());
create policy state_domains_member_read on agenix_hive.state_domains for select to authenticated using (agenix_hive_private.is_any_member());
create policy command_sessions_member_read on agenix_hive.command_sessions for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy commands_member_read on agenix_hive.commands for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy runs_member_read on agenix_hive.runs for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy run_steps_member_read on agenix_hive.run_steps for select to authenticated using (exists (select 1 from agenix_hive.runs r where r.id=run_steps.run_id and agenix_hive_private.is_org_member(r.organization_id)));
create policy resource_leases_member_read on agenix_hive.resource_leases for select to authenticated using (exists (select 1 from agenix_hive.runs r where r.id=resource_leases.run_id and agenix_hive_private.is_org_member(r.organization_id)));
create policy events_member_read on agenix_hive.events for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy event_deliveries_member_read on agenix_hive.event_deliveries for select to authenticated using (exists (select 1 from agenix_hive.events e where e.id=event_deliveries.event_id and agenix_hive_private.is_org_member(e.organization_id)));
create policy artifacts_member_read on agenix_hive.artifacts for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy evidence_receipts_member_read on agenix_hive.evidence_receipts for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy approvals_member_read on agenix_hive.approvals for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy context_snapshots_member_read on agenix_hive.context_snapshots for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy policy_versions_member_read on agenix_hive.policy_versions for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy external_refs_member_read on agenix_hive.external_refs for select to authenticated using (agenix_hive_private.is_org_member(organization_id));
create policy audit_log_member_read on agenix_hive.audit_log for select to authenticated using (agenix_hive_private.is_org_member(organization_id));

grant usage on schema agenix_hive to authenticated, service_role;
grant usage on schema agenix_hive_private to authenticated, service_role;
grant select on all tables in schema agenix_hive to authenticated;
grant all on all tables in schema agenix_hive to service_role;
grant all on all sequences in schema agenix_hive to service_role;
revoke all on function agenix_hive_private.is_org_member(uuid) from public;
revoke all on function agenix_hive_private.is_any_member() from public;
grant execute on function agenix_hive_private.is_org_member(uuid) to authenticated, service_role;
grant execute on function agenix_hive_private.is_any_member() to authenticated, service_role;
revoke all on function agenix_hive_private.set_updated_at() from public;
grant execute on function agenix_hive_private.set_updated_at() to service_role;

alter default privileges in schema agenix_hive grant select on tables to authenticated;
alter default privileges in schema agenix_hive grant all on tables to service_role;
alter default privileges in schema agenix_hive grant all on sequences to service_role;
